### ISSUE TITLE
Create a short snippet to use for programmatic authentication

### ISSUE THREAD

**Issue by dvdokkum** [WXYC/dj-site#37]
I'm going to write a script that runs on a cron to scrape the old (production) flowsheet and enter new entries into the new flowsheet system. In order to do this, I need to programmatically authenticate as a user so I can hit the flowsheet endpoints with the proper credentials. 

@JacksonMeade can you give me a sample script that I can use for this?

**Comment by JacksonMeade** [comment]
[wxyc_login_utility.zip](https://github.com/WXYC/dj-site/files/15448391/wxyc_login_utility.zip)

This should help!
